### PR TITLE
Add method ListLeases

### PR DESCRIPTION
**Pull request by NickCao**
Depends on https://github.com/jumpstarter-dev/jumpstarter-protocol/pull/9

### CODE REVIEW

**Comment by mangelajo** [comment]
I merged the other one, it looks good

**Comment by NickCao** [comment]
> I merged the other one, it looks good

It's merged into https://github.com/jumpstarter-dev/jumpstarter-protocol/pull/7

**Comment by NickCao** [comment]
Found (fixed) another bug when implementing lease: previously only acquired lease can be released early, not pending leases.

**Review by mangelajo — APPROVED** [review]
looks great thanks

**Pull request merged**
